export TAVERNA_HOME="/home/yousee/taverna/taverna-workbench-2.4.0"
export JAVA_HOME="/usr/java/jdk1.6.0_32"

export VHSINGEST_HOME="$HOME/vhs-ingest-workflow/services/workflow"
export VHSINGEST_CONFIG="${config}"
export VHSINGEST_WORKFLOW_CONFIG="${workflow.config}"
export VHSINGEST_LOGS="$HOME/${logs}"
export VHSINGEST_LOCKS="$HOME/var/${locks}"
export VHSINGEST_COMPONENTS="${home}/${components.dir}"
export VHSINGEST_SCRIPTS="${home}/${script.dir}"
export VHSINGEST_WORKFLOWS="${home}/${workflow.dir}"
export VHSINGEST_DEPENDENCIES="${home}/${workflow.dependencies}"
export VHSINGEST_BIN="${home}/${bin}"
