export TAVERNA_HOME="/home/yousee/taverna/taverna-workbench-2.4.0"
export JAVA_HOME="/usr/java/jdk1.6.0_32"

export VHSINGEST_HOME="$HOME/vhs-ingest-workflow/services/workflow"
export VHSINGEST_CONFIG="${vhsingest.config}"
export VHSINGEST_WORKFLOW_CONFIG="${vhsingest.workflow.config}"
export VHSINGEST_LOGS="$HOME/${vhsingest.logs}"
export VHSINGEST_LOCKS="$HOME/var/${vhsingest.locks}"
export VHSINGEST_COMPONENTS="${vhsingest.home}/${vhsingest.components.dir}"
export VHSINGEST_SCRIPTS="${vhsingest.home}/${vhsingest.script.dir}"
export VHSINGEST_WORKFLOWS="${vhsingest.home}/${vhsingest.workflow.dir}"
export VHSINGEST_DEPENDENCIES="${vhsingest.home}/${vhsingest.workflow.dependencies}"
export VHSINGEST_BIN="${vhsingest.home}/${vhsingest.bin}"
